---
language: rust
rust:
  - stable
  - beta
  - nightly
os:
  - linux
sudo: false


cache:
  cargo: true

before_script:
  - cargo clean

script:
  # Build without unstable flag
  - cargo build --release --verbose

  # Test
  - cargo test --verbose -- --nocapture

  - bash -c 'if [[ "$TRAVIS_RUST_VERSION" == "nightly" ]]; then
          cargo +nightly build --features "clippy"
    fi'


deploy:
  provider: script
  script: ci/publish.sh
  skip_cleanup: true
  api-key:
    secure: YUXdO4SZv3+Cm550DGc9WLYRWHaBC4LWYkJK2sbR+GjSkNSvKHfxOe0+pDzJGHNY+QOWKal37H6bCGmk43xHgwWExb0nZ+Vp1nJG/nUeTcglF4tYSX+GJQEOioj1YmaOai0NuJ1peDS8TZXYmbghMc4vnLUnYg7t4gQ3m8M/fVY=
  on:
    tags: true
    all_branches: false



notifications:
  email:
    on_success: never